USE [TECres]
GO

 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Abogado ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Azafata ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Albañil ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Anfitriona ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Arquitecto ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Bombero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Cajero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Camionero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Carnicero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Carpintero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Cartero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Científico ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Cirujano ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Chef ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Cocinero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Comerciante ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Chofer ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Consejero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Constructor  ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Consultor ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Contador ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Asistente ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Dentista ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Detective ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Redactor ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Electricista ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Enfermero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Escritor ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Estibador ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Farmacéutico ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Ferroviario ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Director ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Granjero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Herrero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Ingeniero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Jardinero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Gerente ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Supervisor ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Juez ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Lavandero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Lechero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Licenciado ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Maestro ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Maquinista ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Marinero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Mecánico ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Médico ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Mesero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Panadero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Paramédico ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Pastor ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Periodista ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Pescador ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Pintor ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Plomero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Policía ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Portero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Profesor ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Programador ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Psicólogo ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Psiquiatra ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Químico ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Quiropráctico ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Ganadero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Reparador ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Revisor ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Soldador ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Taxista ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Obrero ')
 INSERT INTO [dbo].[Ocupaciones]([Ocupacion]) VALUES(' Veterinario ')

GO


