CREATE DATABASE TECres


CREATE TABLE Inmueble(
IDInmueble INT IDENTITY PRIMARY KEY NOT NULL,
TipoInmueble VARCHAR (20)
)

CREATE TABLE Piso(
IDPiso INT IDENTITY PRIMARY KEY NOT NULL,
TipoPiso VARCHAR (20)
)

CREATE TABLE Ubicacion(
IDUbicacion INT IDENTITY PRIMARY KEY NOT NULL,
Provincia VARCHAR (20),
Canton VARCHAR (20),
Distrito VARCHAR (50)
)

CREATE TABLE CategoriaAnuncio(
IDAnuncio INT IDENTITY PRIMARY KEY NOT NULL,
NombreAnuncio VARCHAR (10) NOT NULL,
Precio INT NOT NULL,
DescripcionAnuncio VARCHAR (100)
)

CREATE TABLE PublicoMeta(
IDPublicoMeta INT IDENTITY PRIMARY KEY NOT NULL,
Genero VARCHAR (20),
RangoEdad VARCHAR (10) NOT NULL,
Ubicacion VARCHAR (40),
Ingresos INT NOT NULL
)

CREATE TABLE Anuncio(
IDAnuncio INT IDENTITY PRIMARY KEY NOT NULL,
Propiedad INT NOT NULL,
TipoAnuncio INT NOT NULL,
PublicoMeta INT NOT NULL,
FechaInicio VARCHAR (20) NOT NULL,
FechaFin VARCHAR (20) NOT NULL,
TarjetaCredito INT NOT NULL
)

CREATE TABLE Perfiles(
IDPerfil INT IDENTITY PRIMARY KEY NOT NULL,
Perfil VARCHAR (10) NOT NULL
)

CREATE TABLE Ocupaciones(
IDOcupacion INT IDENTITY PRIMARY KEY NOT NULL,
Ocupacion VARCHAR (15) NOT NULL
)

CREATE TABLE TipoFactura (
IDTipoFactura INT IDENTITY PRIMARY KEY NOT NULL,
Tipo VARCHAR (20)
)

CREATE TABLE Comision(
IDComision INT IDENTITY PRIMARY KEY NOT NULL,
Monto INT NOT NULL
)

CREATE TABLE Factura(
IDFactura INT IDENTITY PRIMARY KEY NOT NULL,
Cliente INT NOT NULL,
IDAnuncio INT NOT NULL,
ClaseFactura INT NOT NULL
)

CREATE TABLE Usuario(
Cedula INT PRIMARY KEY NOT NULL,
Nombre VARCHAR (20) NOT NULL,
Apellido1 VARCHAR (20) NOT NULL,
Apellido2 VARCHAR(20) NOT NULL,
FecNaci VARCHAR (10) NOT NULL,
Nacionalidad VARCHAR (20) NOT NULL,
UbicacionUsuario INT NOT NULL,
Ingresos INT NOT NULL,
Ocupacion INT NOT NULL,
Correo VARCHAR (20) NOT NULL,
Perfil INT NOT NULL
)

CREATE TABLE Cuenta(
IDUsuario INT IDENTITY PRIMARY KEY NOT NULL,
Usuario  VARCHAR (20) NOT NULL,
Contrasena VARCHAR (20) NOT NULL
)

CREATE TABLE Propiedad(
IDPropiedad INT IDENTITY PRIMARY KEY,
Titulo VARCHAR (200) NOT NULL,
Descripcion VARCHAR (300),
TipoInmueble INT NOT NULL,
UbicacionPropiedad VARCHAR (100) NOT NULL,
AreaTerreno INT NOT NULL,
AreaConstruccion INT,
Habitaciones INT,
Baños INT,
TipoPiso INT,
Parqueos INT,
Gimnasio VARCHAR (4),
Piscina VARCHAR(4),
ParqueoVisitas VARCHAR (4),
Precio INT NOT NULL,
Dueño INT NOT NULL,
Foto1 IMAGE NOT NULL ,
Foto2 IMAGE NOT NULL ,
Foto3 IMAGE,
Foto4 IMAGE,
Foto5 IMAGE
)

CREATE TABLE Mensaje(
IDMensaje INT IDENTITY PRIMARY KEY NOT NULL,
AnuncioLigado INT NOT NULL,
Remitente INT NOT NULL,
Destinatario INT NOT NULL,
Mensaje VARCHAR (400) NOT NULL
)

CREATE TABLE Administradores(
IDAdministrador INT IDENTITY PRIMARY KEY NOT NULL,
IDUsuario INT NOT NULL,
FechaIngreso VARCHAR (20)
)







ALTER TABLE  ADMINISTRADORES
ADD CONSTRAINT FK_CEDULA FOREIGN KEY (IDUsuario) REFERENCES Usuario(Cedula)

ALTER TABLE  ANUNCIO
ADD CONSTRAINT FK_TipoAnuncio_ID FOREIGN KEY (TipoAnuncio) REFERENCES CategoriaAnuncio(IDAnuncio)
ALTER TABLE ANUNCIO 
ADD CONSTRAINT FK_TipoAnuncio_ID FOREIGN KEY (PublicoMeta) REFERENCES PublicoMeta(IDPublicoMeta)

ALTER TABLE  CUENTA
ADD CONSTRAINT FK_CEDULA FOREIGN KEY (IDUsuario) REFERENCES Usuario(Cedula)

ALTER TABLE  FACTURA
ADD CONSTRAINT FK_ID_ANUNCIO FOREIGN KEY (IDAnuncio) REFERENCES Anuncio(IDAnuncio)
ALTER TABLE  FACTURA
ADD CONSTRAINT FK_TIPO_FACTURA FOREIGN KEY (ClaseFactura) REFERENCES TipoFactura(IDTipoFactura)

ALTER TABLE  MENSAJE
ADD CONSTRAINT FK_ANUNCIO_ID  FOREIGN KEY (AnuncioLigado) REFERENCES Anuncio(IDAnuncio)
ALTER TABLE  MENSAJE
ADD CONSTRAINT FK_REMITENTE FOREIGN KEY (Remitente) REFERENCES Usuario(Cedula)
ALTER TABLE  MENSAJE
ADD CONSTRAINT FK_DESTINATARIO FOREIGN KEY (Destinatario) REFERENCES Usuario(Cedula)

ALTER TABLE  PROPIEDAD
ADD CONSTRAINT FK_CEDULA FOREIGN KEY (Dueño) REFERENCES Usuario(Cedula)
ALTER TABLE  PROPIEDAD
ADD CONSTRAINT FK_ID_TIPO_INMUEBLE FOREIGN KEY (TipoInmueble) REFERENCES Inmueble(IDInmueble)
ALTER TABLE  PROPIEDAD
ADD CONSTRAINT FK_ID_TIPO_PISO FOREIGN KEY (TipoPiso) REFERENCES PISO(IDPiso)

ALTER TABLE  USUARIO
ADD CONSTRAINT FK_ID_PERFIL FOREIGN KEY (Perfil) REFERENCES Perfiles(IDPerfil)
ALTER TABLE  USUARIO
ADD CONSTRAINT FK_ID_OCUPACION FOREIGN KEY (Ocupacion) REFERENCES Ocupaciones(IDOcupacion)
ALTER TABLE  USUARIO
ADD CONSTRAINT FK_ID_UBICACION FOREIGN KEY (UbicacionUsuario) REFERENCES Ubicacion(IDUbicacion)







GO

