CREATE DATABASE TECres

-- CREACIÓN DE LA TABLA INMUEBLE
CREATE TABLE Inmueble(
IDInmueble INT IDENTITY PRIMARY KEY NOT NULL,
TipoInmueble VARCHAR (20)
)

-- CREACIÓN DE LA TABLA PISO
CREATE TABLE Piso(
IDPiso INT IDENTITY PRIMARY KEY NOT NULL,
TipoPiso VARCHAR (20)
)

-- CREACIÓN DE LA TABLA UBICACION
CREATE TABLE Ubicacion(
IDUbicacion INT IDENTITY PRIMARY KEY NOT NULL,
Provincia VARCHAR (20),
Canton VARCHAR (20),
Distrito VARCHAR (50)
)

-- CREACIÓN DE LA TABLA CATEGORIA ANUNCIO
CREATE TABLE CategoriaAnuncio(
IDAnuncio INT IDENTITY PRIMARY KEY NOT NULL,
NombreAnuncio VARCHAR (10) NOT NULL,
TipoAnuncioA INT NOT NULL,
DescripcionAnuncio VARCHAR (200)
)

-- CREACIÓN DE LA TABLA PÚBLICO META
CREATE TABLE PublicoMeta(
IDPublicoMeta INT IDENTITY PRIMARY KEY NOT NULL,
Genero VARCHAR (10),
EdadMinima INT NOT NULL,
EdadMaxima INT NOT NULL,
UbicacionA INT,
Ingresos INT NOT NULL
)

-- CREACIÓN DE LA TABLA ANUNCIO
CREATE TABLE Anuncio(
IDAnuncio INT IDENTITY PRIMARY KEY NOT NULL,
Propiedad INT NOT NULL,
TipoAnuncioA INT NOT NULL,
PublicoMetaA INT NOT NULL,
FechaInicio VARCHAR (20) NOT NULL,
FechaFin VARCHAR (20) NOT NULL,
TarjetaCredito INT NOT NULL,
ComisionA INT NOT NULL
)

-- CREACIÓN DE LA TABLA PERFILES
CREATE TABLE Perfiles(
IDPerfil INT IDENTITY PRIMARY KEY NOT NULL,
Perfil VARCHAR (30) NOT NULL
)

-- CREACIÓN DE LA TABLA OCUPACIONES
CREATE TABLE Ocupaciones(
IDOcupacion INT IDENTITY PRIMARY KEY NOT NULL,
Ocupacion VARCHAR (20) NOT NULL
)

-- CREACIÓN DE LA TABLA TIPO  FACTURA
CREATE TABLE TipoFactura (
IDTipoFactura INT IDENTITY PRIMARY KEY NOT NULL,
Tipo VARCHAR (20)
)

-- CREACIÓN DE LA TABLA TIPO ANUNCIO
CREATE TABLE TipoAnuncio (
IDTipoAnuncio INT IDENTITY PRIMARY KEY NOT NULL,
Tipo VARCHAR (20) NOT NULL,
Precio INT NOT NULL,
)

-- CREACIÓN DE LA TABLA COMISION
CREATE TABLE Comision(
IDComision INT IDENTITY PRIMARY KEY NOT NULL,
Monto INT NOT NULL
)

-- CREACIÓN DE LA TABLA FACTURA
CREATE TABLE Factura(
IDFactura INT IDENTITY PRIMARY KEY NOT NULL,
TipoFacturaA INT NOT NULL,
Cliente INT NOT NULL,
IDAnuncio INT NOT NULL,
MontoTotal INT NOT NULL
)

-- CREACIÓN DE LA TABLA USUARIO
CREATE TABLE Usuario(
Cedula INT PRIMARY KEY NOT NULL,
Nombre VARCHAR (20) NOT NULL,
Apellido1 VARCHAR (20) NOT NULL,
Apellido2 VARCHAR(20) NOT NULL,
FecNaci DATE NOT NULL,
Nacionalidad VARCHAR (30) NOT NULL,
UbicacionUsuario INT NOT NULL,
Ingresos INT NOT NULL,
Ocupacion INT NOT NULL,
Correo VARCHAR (30) NOT NULL,
Perfil INT NOT NULL,
Usuario  VARCHAR (20) NOT NULL,
Contrasena VARCHAR (20) NOT NULL
)

-- CREACIÓN DE LA TABLA PROPIEDAD
CREATE TABLE Propiedad(
IDPropiedad INT IDENTITY PRIMARY KEY,
Titulo VARCHAR (200) NOT NULL,
Descripcion VARCHAR (300),
TipoInmueble INT NOT NULL,
UbicacionPropiedad INT NOT NULL,
AreaTerreno INT NOT NULL,
AreaConstruccion INT,
Habitaciones INT,
Baños INT,
TipoPisoProp INT not null,
Parqueos INT,
Gimnasio VARCHAR (4),
Piscina VARCHAR(4),
ParqueoVisitas VARCHAR (4),
Precio INT NOT NULL,
Dueño INT NOT NULL,
Foto1 IMAGE NOT NULL ,
Foto2 IMAGE NOT NULL ,
Foto3 IMAGE,
Foto4 IMAGE,
Foto5 IMAGE
)

-- CREACIÓN DE LA TABLA MENSAJE
CREATE TABLE Mensaje(
IDMensaje INT IDENTITY PRIMARY KEY NOT NULL,
AnuncioLigado INT NOT NULL,
Remitente INT NOT NULL,
Destinatario INT NOT NULL,
Mensaje VARCHAR (400) NOT NULL
)

-- CREACIÓN DE LA TABLA ADMINISTRADORES
CREATE TABLE Administradores(
IDAdministrador INT IDENTITY PRIMARY KEY NOT NULL,
IDUsuario INT NOT NULL,
FechaIngreso VARCHAR (20)
)


-- FOREIGN KEY DE ADMINISTRADORES
ALTER TABLE  ADMINISTRADORES
ADD CONSTRAINT FK_CEDULA FOREIGN KEY (IDUsuario) REFERENCES Usuario(Cedula)


-- FOREIGN KEY DE ANUNCIO
ALTER TABLE  ANUNCIO
ADD CONSTRAINT FK_TipoAnuncio_ID FOREIGN KEY (TipoAnuncioA) REFERENCES TipoAnuncio(IDTipoAnuncio)
ALTER TABLE ANUNCIO 
ADD CONSTRAINT FK_PublicoMeta_ANUNCIO FOREIGN KEY (PublicoMetaA) REFERENCES PublicoMeta(IDPublicoMeta)
----------------
ALTER TABLE ANUNCIO 
ADD CONSTRAINT FK_Comision_ANUNCIO FOREIGN KEY (ComisionA) REFERENCES Comision(IDComision)

-- FOREIGN KEY DE CATERGORIA ANUNCIO
ALTER TABLE  CATEGORIAANUNCIO
ADD CONSTRAINT FK_TipoAnuncio_CA FOREIGN KEY (TipoAnuncioA) REFERENCES TipoAnuncio(IDTipoAnuncio)



-- FOREIGN KEY DE FACTURA
ALTER TABLE  FACTURA
ADD CONSTRAINT FK_ID_ANUNCIO_FACTURA FOREIGN KEY (IDAnuncio) REFERENCES Anuncio(IDAnuncio)
ALTER TABLE  FACTURA
ADD CONSTRAINT FK_TIPO_FACTURA FOREIGN KEY (TipoFacturaA) REFERENCES TipoFactura(IDTipoFactura)
ALTER TABLE  FACTURA
ADD CONSTRAINT FK_CLIENTE_FACTURA FOREIGN KEY (Cliente) REFERENCES Usuario(Cedula)


-- FOREIGN KEY DE MENSAJE
ALTER TABLE  MENSAJE
ADD CONSTRAINT FK_ANUNCIO_ID_MENSAJE  FOREIGN KEY (AnuncioLigado) REFERENCES Anuncio(IDAnuncio)
ALTER TABLE  MENSAJE
ADD CONSTRAINT FK_REMITENTE_MENSAJE FOREIGN KEY (Remitente) REFERENCES Usuario(Cedula)
ALTER TABLE  MENSAJE
ADD CONSTRAINT FK_DESTINATARIO_MENSAJE FOREIGN KEY (Destinatario) REFERENCES Usuario(Cedula)


-- FOREIGN KEY DE PROPIEDAD
ALTER TABLE  PROPIEDAD
ADD CONSTRAINT FK_CEDULA_PROPIEDAD FOREIGN KEY (Dueño) REFERENCES Usuario(Cedula)
ALTER TABLE  PROPIEDAD
ADD CONSTRAINT FK_ID_TIPO_INMUEBLE_PROPIEDAD FOREIGN KEY (TipoInmueble) REFERENCES Inmueble(IDInmueble)
ALTER TABLE  PROPIEDAD
ADD CONSTRAINT FK_ID_TIPO_PISO FOREIGN KEY (TipoPisoProp) REFERENCES Piso(IDPiso)
ALTER TABLE  PROPIEDAD
ADD CONSTRAINT FK_ID_UBICACION_PROPIEDAD FOREIGN KEY (UbicacionPropiedad) REFERENCES Ubicacion(IDUbicacion)


-- FOREIGN KEY DE USUARIO
ALTER TABLE  USUARIO
ADD CONSTRAINT FK_ID_PERFIL_USUARIO FOREIGN KEY (Perfil) REFERENCES Perfiles(IDPerfil)
ALTER TABLE  USUARIO
ADD CONSTRAINT FK_ID_OCUPACION_USUARIO FOREIGN KEY (Ocupacion) REFERENCES Ocupaciones(IDOcupacion)
ALTER TABLE  USUARIO
ADD CONSTRAINT FK_ID_UBICACION_USUARIO FOREIGN KEY (UbicacionUsuario) REFERENCES Ubicacion(IDUbicacion)


-- FOREIGN KEY DE PUBLICO META
ALTER TABLE  PUBLICOMETA
ADD CONSTRAINT FK_ID_UBICACION_PM FOREIGN KEY (UbicacionA) REFERENCES Ubicacion(IDUbicacion)



GO

-- TABLAS PARA CONTROL DE BORRADO

CREATE TABLE Inmueble_CONTROL(
IDInmueble INT IDENTITY PRIMARY KEY NOT NULL,
TipoInmueble VARCHAR (20),
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Piso_CONTROL(
IDPiso INT IDENTITY PRIMARY KEY NOT NULL,
TipoPiso VARCHAR (20),
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Ubicacion_CONTROL(
IDUbicacion INT IDENTITY PRIMARY KEY NOT NULL,
Provincia VARCHAR (20),
Canton VARCHAR (20),
Distrito VARCHAR (50),
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE CategoriaAnuncio_CONTROL(
IDAnuncio INT IDENTITY PRIMARY KEY NOT NULL,
NombreAnuncio VARCHAR (10) NOT NULL,
TipoAnuncio INT NOT NULL,
DescripcionAnuncio VARCHAR (200),
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE PublicoMeta_CONTROL(
IDPublicoMeta INT IDENTITY PRIMARY KEY NOT NULL,
Genero VARCHAR (10),
EdadMinima INT NOT NULL,
EdadMaxima INT NOT NULL,
Ubicacion INT,
Ingresos INT NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Anuncio_CONTROL(
IDAnuncio INT IDENTITY PRIMARY KEY NOT NULL,
Propiedad INT NOT NULL,
TipoAnuncio INT NOT NULL,
PublicoMeta INT NOT NULL,
FechaInicio VARCHAR (20) NOT NULL,
FechaFin VARCHAR (20) NOT NULL,
TarjetaCredito INT NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Perfiles_CONTROL(
IDPerfil INT IDENTITY PRIMARY KEY NOT NULL,
Perfil VARCHAR (30) NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Ocupaciones_CONTROL(
IDOcupacion INT IDENTITY PRIMARY KEY NOT NULL,
Ocupacion VARCHAR (20) NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE TipoFactura_CONTROL (
IDTipoFactura INT IDENTITY PRIMARY KEY NOT NULL,
Tipo VARCHAR (20),
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE TipoAnuncio_CONTROL (
IDTipoAnuncio INT IDENTITY PRIMARY KEY NOT NULL,
Tipo VARCHAR (20) NOT NULL,
Precio INT NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Comision_CONTROL(
IDComision INT IDENTITY PRIMARY KEY NOT NULL,
Monto INT NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Factura_CONTROL(
IDFactura INT IDENTITY PRIMARY KEY NOT NULL,
TipoFactura INT NOT NULL,
Cliente INT NOT NULL,
IDAnuncio INT NOT NULL,
MontoTotal INT NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Usuario_CONTROL(
Cedula INT PRIMARY KEY NOT NULL,
Nombre VARCHAR (20) NOT NULL,
Apellido1 VARCHAR (20) NOT NULL,
Apellido2 VARCHAR(20) NOT NULL,
FecNaci DATE NOT NULL,
Nacionalidad VARCHAR (30) NOT NULL,
UbicacionUsuario INT NOT NULL,
Ingresos INT NOT NULL,
Ocupacion INT NOT NULL,
Correo VARCHAR (30) NOT NULL,
Perfil INT NOT NULL,
Usuario  VARCHAR (20) NOT NULL,
Contrasena VARCHAR (20) NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)


CREATE TABLE Propiedad_CONTROL(
IDPropiedad INT IDENTITY PRIMARY KEY,
Titulo VARCHAR (200) NOT NULL,
Descripcion VARCHAR (300),
TipoInmueble INT NOT NULL,
UbicacionPropiedad VARCHAR (100) NOT NULL,
AreaTerreno INT NOT NULL,
AreaConstruccion INT,
Habitaciones INT,
Baños INT,
TipoPiso INT,
Parqueos INT,
Gimnasio VARCHAR (4),
Piscina VARCHAR(4),
ParqueoVisitas VARCHAR (4),
Precio INT NOT NULL,
Dueño INT NOT NULL,
Foto1 IMAGE NOT NULL ,
Foto2 IMAGE NOT NULL ,
Foto3 IMAGE,
Foto4 IMAGE,
Foto5 IMAGE,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Mensaje_CONTROL(
IDMensaje INT IDENTITY PRIMARY KEY NOT NULL,
AnuncioLigado INT NOT NULL,
Remitente INT NOT NULL,
Destinatario INT NOT NULL,
Mensaje VARCHAR (400) NOT NULL,
Audit_Action varchar(100),
Audit_Timestamp datetime
)

CREATE TABLE Administradores_CONTROL(
IDAdministrador INT IDENTITY PRIMARY KEY NOT NULL,
IDUsuario INT NOT NULL,
FechaIngreso VARCHAR (20),
Audit_Action varchar(100),
Audit_Timestamp datetime
)

